name: Update Blog

on:
  push:
    paths:
      - 'blog/**'
      - 'blog/images/**'  # Track changes to the images folder

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ensure write access to repository contents

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install --save-dev vite js-yaml markdown-it axios multer express fs

      - name: Upload Image
        run: node blog/upload/upload-image.js

      - name: Generate Blog Posts
        run: node blog/generate-blog.js

      - name: Check changes in index.html
        run: |
          git diff blog/index.html

      - name: Commit updated index.html
        run: |
          git config --global user.email "tenevj@gmail.com"
          git config --global user.name "Jikkata"
          git add blog/index.html blog/images/*
          git commit -m "Update blog posts in index.html" || echo "No changes to commit"
          git diff --cached --exit-code || git commit -m "Update blog posts in index.html"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
