name: Update Blog

on:
  push:
    paths:
      - 'blog/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install --save-dev vite js-yaml

      - name: Generate Blog Posts
        run: node blog/generate-blog.js

      - name: Check changes in index.html
        run: |
          git diff blog/index.html

      - name: Commit updated index.html
        run: |
          git config --global user.email "tenevj@gmail.com"
          git config --global user.name "Jikkata"
          git add blog/index.html
          git commit -m "Update blog posts in index.html" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
