name: Deploy Blog to GitHub Pages

on:
  push:
    branches: 
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: blog
        run: npm install

      - name: Build Site
        working-directory: blog
        run: npm run build
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'

      - name: List Dist Contents
        working-directory: blog
        run: ls -la dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: blog/dist
          branch: gh-pages
          clean: true
